// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Generate():Promise<main.BuildResult>;

export function GetBuilds():Promise<Array<main.BuildInfo>>;

export function GetProjectDir():Promise<string>;

export function RunDecryptor(arg1:string,arg2:string,arg3:string):Promise<string>;

export function RunEncryptor(arg1:string,arg2:string):Promise<string>;

export function SelectFolder():Promise<string>;

export function SelectProjectDir():Promise<string>;
