// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Generate() {
  return window['go']['main']['App']['Generate']();
}

export function GetBuilds() {
  return window['go']['main']['App']['GetBuilds']();
}

export function GetProjectDir() {
  return window['go']['main']['App']['GetProjectDir']();
}

export function RunDecryptor(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunDecryptor'](arg1, arg2, arg3);
}

export function RunEncryptor(arg1, arg2) {
  return window['go']['main']['App']['RunEncryptor'](arg1, arg2);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectProjectDir() {
  return window['go']['main']['App']['SelectProjectDir']();
}
